### ISSUE TITLE
Custom Paths?

### ISSUE THREAD

**Issue by SteveyPugs** [parthasharathi/sftp-watcher#1]
Is it possible for users to look up custom paths?

For example, the upload functionality its great but say I want one for files that end in **txt** vs **csv**. 

Would that be simple regex on the file path?

**Comment by parthasharathi** [comment]
ahhhhhh as of now this feature is not available and your suggestion is a Good idea and good feature as well. I will add the Regax based watcher in the upcoming release. I will post you back once it's done.
