### ISSUE TITLE
Facing issue in the upload event.

### ISSUE THREAD

**Issue by Ponnambalam-thangarasu** [parthasharathi/sftp-watcher#2]
Once upload event bind, It will start to work after uploaded a file into that path but after that, it starts to call that method frequently just like "heartbeat" event.

**Comment by parthasharathi** [comment]
Its might happens due to communication delay time between your server and sftp server.

**Comment by sondredoli** [comment]
Same thing happens here.   

I have 4 watchers running for 2 different FTP-servers. (2 folders on each server).   And 3 of them works fine, but number 4 keeps trigging the "Upload" event several times after it actually happened.

Any one who knows anything more about this, or how to fix it? :)

**Comment by sondredoli** [comment]
Clould you please commit this to NPM?
